development:
  adapter: postgresql
  database: dosap_church_app_development
  host: localhost
  encoding: UTF8
  pool: 5

test: &test
  adapter: postgresql
  database: dosap_church_app_test
  host: localhost
  encoding: UTF8
  pool: 15

production:
  adapter: postgresql
  database: dosap_church_app_production
  host: localhost
  encoding: UTF8
  pool: 15
